services:
  postgres:
    image: postgres:16
    container_name: bench_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: benchdb
    ports:
      - "5432:5432"
